import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white">
      <nav className="border-b border-slate-200">
        <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
          <Link href="/" className="text-lg font-bold text-slate-900">ClipMeta</Link>
        </div>
      </nav>

      <article className="mx-auto max-w-4xl px-6 py-12">
        <h1 className="text-3xl font-bold tracking-tight text-slate-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: March 2026</p>

        <div className="mt-8 space-y-8 text-sm leading-7 text-slate-700">
          <section>
            <h2 className="text-lg font-semibold text-slate-900">1. Acceptance of Terms</h2>
            <p className="mt-3">By accessing or using ClipMeta, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">2. Description of Service</h2>
            <p className="mt-3">ClipMeta is a metadata workflow tool for stock footage contributors. It allows users to upload video clips, generate AI-assisted metadata, review and edit results, and export CSV files for submission to stock footage platforms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">3. User Accounts</h2>
            <p className="mt-3">You are responsible for maintaining the security of your account and password. ClipMeta cannot and will not be liable for any loss or damage from your failure to comply with this security obligation.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">4. Your Content</h2>
            <p className="mt-3">You retain ownership of the video clips and metadata you create using ClipMeta. By uploading content, you grant ClipMeta a limited license to process and store that content for the purpose of providing the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">5. Acceptable Use</h2>
            <p className="mt-3">You agree not to use ClipMeta to upload illegal content, infringe on intellectual property rights, or engage in any activity that violates applicable law.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">6. AI-Generated Content</h2>
            <p className="mt-3">Metadata generated by ClipMeta is AI-assisted and may contain errors. You are responsible for reviewing and verifying all generated metadata before submitting it to stock platforms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">7. Termination</h2>
            <p className="mt-3">We reserve the right to terminate or suspend access to the service at any time, with or without cause, with or without notice.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">8. Disclaimer of Warranties</h2>
            <p className="mt-3">ClipMeta is provided &quot;as is&quot; without warranties of any kind, express or implied. We do not guarantee that the service will be error-free or uninterrupted.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">9. Limitation of Liability</h2>
            <p className="mt-3">ClipMeta shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900">10. Contact</h2>
            <p className="mt-3">Questions about these Terms? Contact us at <a href="mailto:hello@clipmeta.com" className="text-slate-900 underline">hello@clipmeta.com</a>.</p>
          </section>
        </div>
      </article>

      <footer className="border-t border-slate-200 py-8">
        <div className="mx-auto flex max-w-4xl flex-wrap gap-6 px-6 text-sm text-slate-500">
          <Link href="/legal/privacy" className="hover:text-slate-900">Privacy Policy</Link>
          <Link href="/pricing" className="hover:text-slate-900">Pricing</Link>
        </div>
      </footer>
    </main>
  );
}
