import Link from "next/link";
import type { Metadata } from "next";
import EmailCapture from "@/components/EmailCapture";
import { FlightDeckShell } from "@/components/landing/FlightDeckShell";

export const metadata: Metadata = {
  title: "AI Metadata for Stock Footage Contributors | ClipMeta",
  description:
    "Upload clips, get AI-generated titles, descriptions, and keywords. Export CSV for Blackbox, Pond5, Adobe Stock, Shutterstock. Free to start.",
};

export default function SocialLandingPage() {
  return (
    <FlightDeckShell>

      {/* Hero */}
      <section className="mx-auto max-w-5xl px-6 py-20 text-center">
        <div className="inline-block rounded-full border border-blue-400/30 bg-blue-500/10 px-4 py-1.5 text-sm font-medium text-blue-200">
          Built for stock footage contributors
        </div>
        <h1 className="mt-6 text-4xl font-bold tracking-tight text-white md:text-5xl lg:text-6xl">
          AI metadata for your
          <br />
          <span className="gradient-text">stock footage clips</span>
        </h1>
        <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/60">
          Upload your clips and get platform-ready titles, descriptions, and keywords generated by AI.
          Review and edit everything, then export a submission-ready CSV for Blackbox, Pond5,
          Adobe Stock, or Shutterstock.
        </p>
        <div className="mt-10 flex flex-wrap items-center justify-center gap-4">
          <Link
            href="/sign-up"
            className="rounded-lg bg-gradient-to-r from-violet-600 to-violet-500 px-7 py-3.5 text-base font-semibold text-white shadow-lg shadow-violet-500/30 transition hover:shadow-xl hover:shadow-violet-500/50"
          >
            Get Started Free
          </Link>
          <Link
            href="/auth"
            className="rounded-lg border border-white/15 px-7 py-3.5 text-base font-semibold text-white/75 transition hover:bg-white/5"
          >
            Sign In
          </Link>
        </div>
        <p className="mt-4 text-sm text-white/60">
          No credit card required.
        </p>
      </section>

      {/* Stats / trust strip */}
      <section className="relative border-y border-white/10 py-10">
        <div className="mx-auto max-w-4xl px-6">
          <div className="grid grid-cols-2 gap-6 text-center md:grid-cols-4">
            {[
              { value: "30–50", label: "Keywords per clip" },
              { value: "4", label: "Platform formats" },
              { value: "1-click", label: "CSV export" },
              { value: "100%", label: "Editable before export" },
            ].map((stat) => (
              <div key={stat.label}>
                <p className="text-2xl font-bold text-white">{stat.value}</p>
                <p className="mt-1 text-sm text-white/60">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-20">
        <div className="mx-auto max-w-5xl px-6">
          <p className="hud-chip mx-auto mb-3 inline-flex">
            How it works
          </p>
          <h2 className="mt-3 text-center text-3xl font-bold text-white">
            From upload to submitted in minutes
          </h2>
          <div className="mt-12 grid gap-8 md:grid-cols-3">
            {[
              {
                step: "1",
                icon: "📤",
                title: "Upload your clips",
                body: "Create a project, add your footage. ClipMeta extracts frames automatically to analyze each clip.",
              },
              {
                step: "2",
                icon: "🤖",
                title: "AI generates metadata",
                body: "Titles, descriptions, keywords, categories, and location — all generated and scored for stock platform relevance.",
              },
              {
                step: "3",
                icon: "📋",
                title: "Review, edit, export",
                body: "Every field is editable inline. When you're happy, export a CSV formatted for your target platform.",
              },
            ].map((item) => (
              <div key={item.step} className="glass-card relative p-8">
                <div className="absolute -top-4 left-6 flex h-8 w-8 items-center justify-center rounded-full bg-gradient-to-r from-violet-600 to-violet-500 text-sm font-bold text-white shadow-lg shadow-violet-500/30">
                  {item.step}
                </div>
                <div className="mt-2 text-3xl">{item.icon}</div>
                <h3 className="mt-4 text-lg font-semibold text-white">{item.title}</h3>
                <p className="mt-3 text-sm leading-6 text-white/60">{item.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <EmailCapture source="social" />

      {/* Features */}
      <section className="relative border-t border-white/10 py-16">
        <div className="mx-auto max-w-5xl px-6">
          <h2 className="text-center text-2xl font-bold text-white">
            Everything you need to ship your backlog
          </h2>
          <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {[
              { icon: "🎯", title: "Stock-specific keywords", body: "AI trained on what buyers actually search for on stock platforms. Not generic SEO terms." },
              { icon: "📊", title: "Quality scoring", body: "Each keyword gets a quality score so you can spot and replace weak ones before export." },
              { icon: "⚡", title: "Batch generation", body: "Process an entire project at once. Dozens of clips keyworded while you take a break." },
              { icon: "✏️", title: "Inline editing", body: "Click any field to edit. Drag to reorder keywords. You're always in control." },
              { icon: "🌍", title: "Multi-platform CSV", body: "Export in the exact format each platform expects: Blackbox, Pond5, Adobe Stock, Shutterstock." },
              { icon: "📁", title: "Project organization", body: "Group clips into projects. Keep different shoots separate and export independently." },
            ].map((item) => (
              <div key={item.title} className="glass-card p-6">
                <div className="text-2xl">{item.icon}</div>
                <h3 className="mt-3 font-semibold text-white">{item.title}</h3>
                <p className="mt-2 text-sm leading-6 text-white/60">{item.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20">
        <div className="mx-auto max-w-2xl px-6 text-center">
          <h2 className="text-3xl font-bold text-white">
            Ready to clear your footage backlog?
          </h2>
          <p className="mt-4 text-lg text-white/60">
            Start your first project for free. No credit card, no commitment.
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
            <Link
              href="/sign-up"
              className="inline-block rounded-lg bg-gradient-to-r from-violet-600 to-violet-500 px-8 py-4 text-base font-semibold text-white shadow-lg shadow-violet-500/30 transition hover:shadow-xl hover:shadow-violet-500/50"
            >
              Create Free Account
            </Link>
          </div>
          <p className="mt-4 text-sm text-white/60">
            Works with Blackbox.global, Pond5, Adobe Stock, and Shutterstock.
          </p>
        </div>
      </section>

    </FlightDeckShell>
  );
}
