import Link from "next/link";
import type { Metadata } from "next";
import EmailCapture from "@/components/EmailCapture";

export const metadata: Metadata = {
  title: "AI Metadata for Stock Footage Contributors | ClipMeta",
  description:
    "Upload clips, get AI-generated titles, descriptions, and keywords. Export CSV for Blackbox, Pond5, Adobe Stock, Shutterstock. Free to start.",
};

export default function SocialLandingPage() {
  return (
    <main className="min-h-screen bg-background">

      {/* Nav */}
      <nav className="border-b border-border">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          <span className="flex items-center gap-2 text-lg font-bold text-foreground">
            <img src="/logo-icon.svg" className="h-7 w-7" alt="ClipMeta" />
            ClipMeta
          </span>
          <Link
            href="/sign-up"
            className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white transition hover:bg-slate-800"
          >
            Try Free
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="mx-auto max-w-5xl px-6 py-20 text-center">
        <div className="inline-block rounded-full bg-blue-100 px-4 py-1.5 text-sm font-medium text-blue-800">
          Built for stock footage contributors
        </div>
        <h1 className="mt-6 text-4xl font-bold tracking-tight text-slate-900 md:text-5xl lg:text-6xl">
          AI metadata for your
          <br />
          <span className="text-slate-500">stock footage clips</span>
        </h1>
        <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">
          Upload your clips and get platform-ready titles, descriptions, and keywords generated by AI.
          Review and edit everything, then export a submission-ready CSV for Blackbox, Pond5,
          Adobe Stock, or Shutterstock.
        </p>
        <div className="mt-10 flex flex-wrap items-center justify-center gap-4">
          <Link
            href="/sign-up"
            className="rounded-lg bg-slate-900 px-7 py-3.5 text-base font-semibold text-white transition hover:bg-slate-700"
          >
            Get Started Free
          </Link>
          <Link
            href="/auth"
            className="rounded-lg border border-slate-300 px-7 py-3.5 text-base font-semibold text-slate-700 transition hover:bg-muted"
          >
            Sign In
          </Link>
        </div>
        <p className="mt-4 text-sm text-muted-foreground">
          No credit card required.
        </p>
      </section>

      {/* Stats / trust strip */}
      <section className="border-y border-slate-100 bg-slate-50 py-10">
        <div className="mx-auto max-w-4xl px-6">
          <div className="grid grid-cols-2 gap-6 text-center md:grid-cols-4">
            {[
              { value: "30–50", label: "Keywords per clip" },
              { value: "4", label: "Platform formats" },
              { value: "1-click", label: "CSV export" },
              { value: "100%", label: "Editable before export" },
            ].map((stat) => (
              <div key={stat.label}>
                <p className="text-2xl font-bold text-slate-900">{stat.value}</p>
                <p className="mt-1 text-sm text-muted-foreground">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-20">
        <div className="mx-auto max-w-5xl px-6">
          <p className="text-center text-sm font-semibold uppercase tracking-widest text-muted-foreground">
            How it works
          </p>
          <h2 className="mt-3 text-center text-3xl font-bold text-slate-900">
            From upload to submitted in minutes
          </h2>
          <div className="mt-12 grid gap-8 md:grid-cols-3">
            {[
              {
                step: "1",
                icon: "📤",
                title: "Upload your clips",
                body: "Create a project, add your footage. ClipMeta extracts frames automatically to analyze each clip.",
              },
              {
                step: "2",
                icon: "🤖",
                title: "AI generates metadata",
                body: "Titles, descriptions, keywords, categories, and location — all generated and scored for stock platform relevance.",
              },
              {
                step: "3",
                icon: "📋",
                title: "Review, edit, export",
                body: "Every field is editable inline. When you're happy, export a CSV formatted for your target platform.",
              },
            ].map((item) => (
              <div key={item.step} className="relative rounded-2xl border border-slate-200 bg-card p-8 shadow-sm">
                <div className="absolute -top-4 left-6 flex h-8 w-8 items-center justify-center rounded-full bg-slate-900 text-sm font-bold text-white">
                  {item.step}
                </div>
                <div className="mt-2 text-3xl">{item.icon}</div>
                <h3 className="mt-4 text-lg font-semibold text-foreground">{item.title}</h3>
                <p className="mt-3 text-sm leading-6 text-muted-foreground">{item.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <EmailCapture source="social" />

      {/* Features */}
      <section className="border-t border-slate-100 bg-muted/50 py-16">
        <div className="mx-auto max-w-5xl px-6">
          <h2 className="text-center text-2xl font-bold text-slate-900">
            Everything you need to ship your backlog
          </h2>
          <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {[
              { icon: "🎯", title: "Stock-specific keywords", body: "AI trained on what buyers actually search for on stock platforms. Not generic SEO terms." },
              { icon: "📊", title: "Quality scoring", body: "Each keyword gets a quality score so you can spot and replace weak ones before export." },
              { icon: "⚡", title: "Batch generation", body: "Process an entire project at once. Dozens of clips keyworded while you take a break." },
              { icon: "✏️", title: "Inline editing", body: "Click any field to edit. Drag to reorder keywords. You're always in control." },
              { icon: "🌍", title: "Multi-platform CSV", body: "Export in the exact format each platform expects: Blackbox, Pond5, Adobe Stock, Shutterstock." },
              { icon: "📁", title: "Project organization", body: "Group clips into projects. Keep different shoots separate and export independently." },
            ].map((item) => (
              <div key={item.title} className="rounded-xl border border-slate-200 bg-card p-6 shadow-sm">
                <div className="text-2xl">{item.icon}</div>
                <h3 className="mt-3 font-semibold text-foreground">{item.title}</h3>
                <p className="mt-2 text-sm leading-6 text-muted-foreground">{item.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20">
        <div className="mx-auto max-w-2xl px-6 text-center">
          <h2 className="text-3xl font-bold text-slate-900">
            Ready to clear your footage backlog?
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            Start your first project for free. No credit card, no commitment.
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
            <Link
              href="/sign-up"
              className="inline-block rounded-lg bg-slate-900 px-8 py-4 text-base font-semibold text-white transition hover:bg-slate-700"
            >
              Create Free Account
            </Link>
          </div>
          <p className="mt-4 text-sm text-muted-foreground">
            Works with Blackbox.global, Pond5, Adobe Stock, and Shutterstock.
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-200 py-8">
        <div className="mx-auto flex max-w-5xl flex-wrap items-center justify-center gap-6 px-6 text-sm text-muted-foreground">
          <span className="flex items-center gap-1.5">
            <img src="/logo-icon.svg" className="h-4 w-4" alt="" />
            © 2026 ClipMeta
          </span>
          <Link href="/pricing" className="hover:text-foreground">Pricing</Link>
          <Link href="/legal/terms" className="hover:text-foreground">Terms</Link>
          <Link href="/legal/privacy" className="hover:text-foreground">Privacy</Link>
        </div>
      </footer>

    </main>
  );
}
